### ISSUE TITLE
Stream is not seekable (for reading)

### ISSUE THREAD

**Issue by chapa** [chrisnharvey/flysystem-openstack-swift#16] opened 2019-11-18 22:08 UTC
Hi !

It takes me a long time to figure out how to effectively redirect a stream from Flysystem (with this Openstack Swift adapter) to the web client, without having the file completely downloaded on the server before starting to sending it (to the client).

I found that Guzzle (which is internally used by `php-opencloud/openstack`) has an option [`'stream'`](http://docs.guzzlephp.org/en/stable/request-options.html#stream-option) to "stream a response rather than download it all up-front". This option has to be given to the `Client` constructor.\
`Client` is constructed internally by `OpenStack`, but you can give its options to the latter's constructor with a `'requestOptions`' option (code : https://github.com/php-opencloud/openstack/blob/v3.0.6/src/OpenStack.php#L72, didn't find anything in the doc though).

Fact is that the stream returned by Guzzle to Openstack to this Flysystem adapter is different when the `'stream'` option is set to `true` and more particularly is not seekable, as you can see in the left dump :
![image](https://user-images.githubusercontent.com/457659/69096150-27d4a780-0a54-11ea-855f-2b4c58d36541.png) ![image](https://user-images.githubusercontent.com/457659/69096272-61a5ae00-0a54-11ea-9b1c-3a9232a1f114.png)
(left: with the option, right: without)

The problem is that methods `read()` and `readStream()` of this adapter rewind the stream before returning it, and it causes an exception "Stream is not seekable" to be [thrown](https://github.com/guzzle/psr7/blob/1.6.0/src/Stream.php#L201).

https://github.com/nimbusoftltd/flysystem-openstack-swift/blob/780b3cbbdeaac099145c3d1a09824c24498fb6a0/src/SwiftAdapter.php#L185
https://github.com/nimbusoftltd/flysystem-openstack-swift/blob/780b3cbbdeaac099145c3d1a09824c24498fb6a0/src/SwiftAdapter.php#L200

Is there any reason for having these lines, or is it possible to remove them ?

**Comment by mzur** [comment] 2019-11-19 09:12
The call to `rewind` is a workaround for a bug (?) in the OpenStack library ( #6 ). I think it should be ok to check if the stream is seekable in `readStream` and only rewind if this is `true`. Would this work for you @chapa?

**Comment by chapa** [comment] 2019-11-19 09:26
Thanks for the explanation, yes that would be perfect !

**Comment by mzur** [comment] 2019-11-19 10:53
I'm not sure about `read`. The expected behavior here is to get the content of the whole file. It shouldn't matter for your use case, anyway, right? Or does it throw the exception, too, because of your custom `requestOptions`?

**Comment by chapa** [comment] 2019-11-19 16:10
Indeed it also throws the exception with `read`, because of the `requestOptions`.

Anyway it's safer to check if the stream is seekable before rewind it, no matter what, dont you think ?

**Comment by mzur** [comment] 2019-11-20 08:02
> Anyway it's safer to check if the stream is seekable before rewind it, no matter what, dont you think ?

Yeah, it shouldn't hurt. Please send a PR with this change and appropriate tests (if possible).

**Comment by chapa** [comment] 2019-11-20 08:59
I will, but first I have to look at something on the OpenStack side.

I realized that I can't use the `'stream'` option without doing some complicated workaround when building the `OpenStack` object, because `Identity` doesn't support streams for getting the auth token.\
And since the `'stream'` option is given globally to the Guzzle `Client`, it's also used in this `Identity` object that get the auth token but can't handle this kind of streams.

I'm thinking about asking to `php-opencloud/openstack` if it's possible to allow passing Guzzle options individually for each request (e.g. `$object->download($options)`).

If it became possible, don't you think this adapter should itself set the `'stream'` option in the `readStream` method ?\
Personally I'm a bit confused with a `setStream` method that actually download the whole remote file before returning its content in a stream...

**Comment by mzur** [comment] 2019-11-20 09:14
Which `setStream` method do you mean? Using the `download` method of OpenStack shouldn't download the whole object. At least it says so in the [comment](https://github.com/php-opencloud/openstack/blob/3eba351cd04cf73a54984334e5da2fe4cf6efe1a/src/ObjectStore/v1/Models/StorageObject.php#L140-L141).

**Comment by chapa** [comment] 2019-11-20 09:21
I mean the `setStream` method of this adapter.

I saw that comment, but it's not what I see : if I don't set the `'stream'` option to `true`, the whole object is downloaded before the stream is returned by `$object->download()`.

**Comment by chapa** [comment] 2019-11-20 22:11
FYI https://github.com/php-opencloud/openstack/issues/292

**Comment by mzur** [comment] 2019-11-21 09:23
Sorry but I couldn't find a `setStream` method. Anyway, the main problem should be the unexpected download as you already mentioned. Let's see if somebody responds over at the OpenStack repository. It's rather inactive, I'm afraid.

**Comment by chapa** [comment] 2019-11-21 09:31
Lol sorry I didn't mean `setStream` but `readStream` ! :joy:

I'm afraid too, let's wait some days and we'll see.

**Comment by mzur** [comment] 2022-02-17 13:19
Was this fixed by php-opencloud/openstack#299?

**Comment by chapa** [comment] 2022-02-17 13:41
I think there still be a problem when the guzzle client is configured with `'stream' => true` as [`$stream->rewind()`](https://github.com/chrisnharvey/flysystem-openstack-swift/blob/0a343cf4533b7bc38b57f1265c37b64ce6a50d06/src/SwiftAdapter.php#L184) is always called in `read()` whether the stream is seekable or not. It must be worth it to do this only if `$stream->isSeekable()`.

Also, this is not directly related to this issue but the `readStream()` method doesn't give `['stream' => true]` to the `download()` method [here](https://github.com/chrisnharvey/flysystem-openstack-swift/blob/0a343cf4533b7bc38b57f1265c37b64ce6a50d06/src/SwiftAdapter.php#L199), so by default the whole object is downloaded before the method returns. This is the thing that can be done thanks to https://github.com/php-opencloud/openstack/pull/299

**Closed** 2022-06-10 06:54 UTC
